import { createConstants } from "../utils";

export default createConstants(
  "USER_LOGIN_REQUEST",
  "USER_LOGIN_SUCCESS",
  "USER_LOGIN_FAILURE",
  "USER_LOGOUT",
  "CHECKIN_CUSTOMER",
  "SERVICES_FETCH_REQUEST",
  "SERVICES_FETCH_SUCCESS",
  "SERVICES_FETCH_FAILURE",
  "NEW_PRODUCTS_FETCH_REQUEST",
  "NEW_PRODUCTS_FETCH_SUCCESS",
  "NEW_PRODUCTS_FETCH_FAILURE"
);
